llvmdev:
  - 20
llvm:
  - 20
mlir:
  - 20
libmlir:
  - 20

cuda_compiler_version:
  - 12.8

#llvmdev:
#  - 21.1
#llvm:
#  - 21.1
#mlir:
#  - 21.1
#libmlir:
#  - 21.1
#zlib:
#  - 1.3

# # The package fails to build against CUDA 12.0, upstream uses 12.4.99,
# # let's just use 12.6.
# c_stdlib_version:                                 # [linux64]
#   - 2.28                                          # [linux64]
# docker_image:                                     # [linux64]
#   - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux64]
# c_compiler_version:                               # [linux64]
#   - 13                                            # [linux64]
# cxx_compiler_version:                             # [linux64]
#   - 13                                            # [linux64]
# fortran_compiler_version:                         # [linux64]
#   - 13                                            # [linux64]
# cdt_name:                                         # [linux64]
#   - cos7                                          # [linux64]
# cuda_compiler:                                    # [linux64]
#   - cuda-nvcc                                     # [linux64]
# cuda_compiler_version:                            # [linux64]
#   - 12.6                                          # [linux64]
